{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_pytest.test_feature_story.TestLogin object at 0x000001BD3E811FC8>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1'==1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:27: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1589117668266, "stop": 1589117668266}, {"name": "点击密码", "status": "passed", "start": 1589117668266, "stop": 1589117668266}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"F:\\Python\\TestDevelopment\\test_pytest\\test_feature_story.py\", line 27, in test_login_failure\n    assert '1'==1\n"}, "start": 1589117668266, "stop": 1589117668266}], "attachments": [{"name": "stdout", "source": "5c7666f8-074d-4e88-9e52-b6ca37cffc68-attachment.txt", "type": "text/plain"}], "start": 1589117668266, "stop": 1589117668266, "uuid": "a930a376-059e-4da4-ac41-9397f692a6c9", "historyId": "a58c5550e5c40eb80abda2e84e87077a", "testCaseId": "a0fb827149424dbc77d431148fe9f888", "fullName": "test_feature_story.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-HJ7N9JB"}, {"name": "thread", "value": "15936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}